const gameState = {
      playerHealth: 100,
      maxHealth: 100,
      score: 0,
      level: 1,
      zombiesDestroyed: 0,
      zombiesTotal: 5,
      zombies: [],
      projectiles: [],
      isReloading: false,
      gameOver: false,
      nightVision: false,
      powerUps: [],
      isShooting: false,
      lastShotPosition: null,
      shotNoiseRadius: 30,
      zombieChaseSpeedBoost: 2,
      zombieChaseDuration: 3,
      powerUpSpawnTimer: 0,
      powerUpSpawnInterval: 10,

      gameDay: 1,
      lastWeatherChangeDay: 0,
      currentWeather: 'clear',
      weatherEffectDuration: 60,
      weatherTimer: 0,
      lightningFlickerTimer: 0,
      isLightningActive: false,
      lightningDuration: 0.1,
      lightningInterval: 5,

      lightningZombieExists: false,
      lightningStrikeRandomTimer: 0,
      lightningStrikeRandomIntervalMin: 90,
      lightningStrikeRandomIntervalMax: 270,

      weapons: {
        rifle: {
          name: "FUCILE",
          ammo: 30,
          maxAmmo: 300,
          clipSize: 30,
          fireRate: 0.1,
          damage: 10,
          mesh: null,
          isShooting: false,
          lastShotTime: 0,
          recoilAmount: 0.05,
          recoilDuration: 70,
        },
        shotgun: {
          name: "FUCILE A POMPA",
          ammo: 10,
          maxAmmo: 100,
          clipSize: 8,
          fireRate: 0.8,
          damage: 25,
          pellets: 5,
          spreadAngle: 0.1,
          mesh: null,
          isShooting: false,
          lastShotTime: 0,
          recoilAmount: 0.15,
          recoilDuration: 150,
        }
      },
      currentWeapon: 'rifle',

      inVehicle: false,
      vehicleSpeed: 15.0,
      vehicleRotationSpeed: 0.05,
      vehicleFuel: 100,
      maxVehicleFuel: 100,
      vehicleDistanceTraveled: 0,
      vehicleFuelConsumptionRate: 0.0005,
      vehicleKmPerUnit: 0.01,
      vehicleWeapons: {
        machineGun: {
          name: "MITRAGLIATRICE",
          ammo: 500,
          maxAmmo: 1000,
          fireRate: 0.05,
          damage: 20,
          isShooting: false,
          lastShotTime: 0,
          muzzleFlashLight: null,
          muzzleFlashMesh: null,
        },
        cannon: {
          name: "CANNONE",
          ammo: 5,
          maxAmmo: 10,
          fireRate: 2.0,
          damage: 500,
          aoeRadius: 15,
          isShooting: false,
          lastShotTime: 0,
        }
      },
      currentVehicleWeapon: 'machineGun',

      destructibleRocks: [],
      maxDestructibleRocks: 5,
      rockSpawnTimer: 0,
      rockSpawnInterval: 10,
      isDamageBoostActive: false,
      damageBoostTimer: 0,
      damageBoostDuration: 7,
      damageBoostMultiplier: 2,

      isDistorted: false,
      distortionTimer: 0,
      distortionDuration: 1.5,
      distortionOverlay: null,

      isCloudStormActive: false,
      cloudStormTimer: 0,
      cloudStormLightningTimer: 0,
      atmosphericExplosionDuration: 3,
      triggeredRainDuration: 18,

      isSpeedBoostActive: false,
      speedBoostTimer: 0,
      speedBoostDuration: 7,
      speedBoostMultiplier: 1.5,

      resources: 0,
      isCraftingMenuOpen: false,

      vehicleIsVulnerable: false,
      vehicleVulnerabilityTimer: 0,
      vehicleVulnerabilityDuration: 10,
      vehicleOriginalMaterial: null,

      currentObjective: null,
      objectiveTimer: 0,
      objectiveDuration: 60,
      lighthouseMesh: null,
    };

export default gameState;
